### ISSUE TITLE
Improve exception when StaticFieldsInvariantRule hits SecurityException

### ISSUE THREAD

**Issue by rmuir** [carrotsearch/randomizedtesting#189]
When running tests inside a securitymanager, the RUE crawl in this rule can cause securityexceptions (because you leaked a class with JDK stuff, and then it ultimately calls setAccessible() on a JDK-internal impl class).

This can be confusing to developers to debug, because they don't know what is happening. I think its worth a try/catch in AfterAlways to give a better exception, informing the user they have a static leak, but we hit securityexception trying to determine how large it was.

**Comment by dweiss** [comment]
Noted, thanks Robert.
